if(typeof jQuery==="undefined"){alert("AJC ERROR : Undefined jQuery [http://code.jquery.com/jquery.min.js]");}
if(typeof JSON==="undefined"||typeof JSON.stringify!=='function'||typeof JSON.parse!=='function'){alert("AJC ERROR : Undefined JSON [http://www.JSON.org/json2.js]");}(function(){var aa=false,fnTest=/xyz/.test(function(){xyz;})?/\b_super\b/:/.*/;this.Class=function(){};Class.extend=function(ba){var ca=this.prototype;aa=true;var da=new this();aa=false;for(var ea in ba){da[ea]=typeof ba[ea]=="function"&&typeof ca[ea]=="function"&&fnTest.test(ba[ea])?(function(ea,fn){return function(){var fa=this._super;this._super=ca[ea];var ga=fn.apply(this,arguments);this._super=fa;return ga;};})(ea,ba[ea]):ba[ea];}
function Class(){if(!aa&&this.init)this.init.apply(this,arguments);}
Class.prototype=da;Class.prototype.constructor=Class;Class.extend=arguments.callee;return Class;};})();function consoleLog(ha){if(typeof console!='undefined'){console.log(ha);}}
var FORM=Class.extend({onBeforeSubmit:function(){},onSubmit:function(){},init:function(ia){this.d={};if(typeof ia==="string"&&ia.indexOf("#")==0&&$(ia).is("form")){this.f=$(ia);}
else if(typeof ia!=="string"&&$(ia).is("form")){this.f=$(ia);}
else{this.f=$("<form>").attr({action:ia,method:"post"}).appendTo(document.body);}},attr:function(a){if($.isPlainObject(a)){this.f.attr(a);return this;}
else if(typeof a==='string'){return this.f.attr(a);}
return this;},data:function(){var ja=arguments;var ka=ja.length;if(ka==2){this.d[ja[0]]=ja[1];}
else if($.isPlainObject(ja)){this.d=$.mg(this.d,ja[0]);}
return this;},submit:function(){var la=this;this.onBeforeSubmit(this);$.each(this.d,function(k,v){var e=$(la.f).find("[name="+k+"]");if(e.length==0)e=$("<input type='hidden'>").attr({name:k}).appendTo(la.f);e.val(v);});this.f.get(0).submit();this.onSubmit(this);return this;},upload:function(ma,na){var oa=this;var pa=0;this.f.find("input:file").each(function(){if(this.value)pa++;});if(pa==0){na.call(oa.f.get(0),null);}
else{var qa="____FILEUPLOADFRAME____";this.attr({target:qa,action:ma});$("iframe[name="+qa+"]").remove();var ra=$("<iframe>").attr({name:qa}).appendTo(document.body).hide();ra.ready(function(){ra.load(function(){var ta=ma.indexOf("http://")==-1?ra.contents().text():"Unsafe JavaScript attempt to access frame with URL "+document.domain+" from frame with URL "+ma+". Domains, protocols or ports must match.";if(na)na.call(oa.f.get(0),ta);});oa.submit();});}}});var AJC=Class.extend({onAjaxBeforeSend:function(ua){ua.setRequestHeader("JSON","JSON");ua.setRequestHeader("ajax","true");},init:function(){this.type=null;this.opts={width:'0px',height:'0px',scrollbars:'no'};this.ds={};this.target=null;this.callback=null;},data:function(ds){this.ds=ds;return this;},args:function(a){var va=[];$.each(a,function(k,v){if($(v).is("form"))va.push($(v).so());else va.push(v);});return JSON.stringify(va);},action:function(wa,u,xa){var ya=this;var za=this.type||wa;var Aa=null;var Ba=this.ds;var Ca=Ba;if(xa!=null&&xa.length!=0){var v=this.args(xa);Ba=$.mg({JSON:v},Ba);Ca=$.mg({JSON:xa},Ca);}
consoleLog(Ca);if(za=="href"){var Da=new FORM(u);if($.isEmptyObject(Ba))Da.attr({method:'GET'});Da.data(Ba).submit();}
else if(za=="popup"){var sw=screen.availWidth;var sh=screen.availHeight;if(this.opts.position){if(this.opts.position.toLowerCase()=="top"){this.opts.left=(sw-this.opts.width)/2;this.opts.top=0;}
else if(this.opts.position.toLowerCase()=="bottom"){this.opts.left=(sw-this.opts.width)/2;}
else if(this.opts.position.toLowerCase()=="left"){this.opts.left=0;this.opts.top=(sh-this.opts.height)/2;}
else if(this.opts.position.toLowerCase()=="right"){this.opts.top=(sh-this.opts.height)/2;}
else{this.opts.left=(sw-this.opts.width)/2;this.opts.top=(sh-this.opts.height)/2;}
delete this.opts.position;}
if(this.opts.autoResize){delete this.opts.autoResize;}
var Ea=[];$.each(this.opts,function(k,v){var k1=k.toLowerCase();if(k1=="width"||k1=="height"||k1=="left"||k1=="top")Ea.push(k+"="+v+"px");else Ea.push(k+"="+v);});var Fa=Ea.join(",");var w=window.open("about:blank",this.target,Fa);var Da=new FORM(u);Da.attr({target:this.target});if($.isEmptyObject(Ba))Da.attr({method:'GET'});Da.data(Ba).submit();}
else if(za=="load"){var Ga=this.callback;var Ha=typeof this.target==="string"?$("#"+this.target):$(this.target);Ha.load(u,Ba,function(Ia,Ja,Ka){if(Ka.getResponseHeader('content-type').indexOf('json')!=-1){var d=JSON.parse(Ia);if(d.code=="error"){alert(d.msg);return false;}}
else{if(Ga!=null){Ga.call(Ha);ya.callback=null;}}});}
else{$.ajax({cache:false,type:"POST",url:u,data:Ba,beforeSend:this.onAjaxBeforeSend,async:false,success:function(t1){Aa=t1;if($.isPlainObject(Aa)){if(Aa.msg)alert(Aa.msg);if(Aa.code==="error"){Aa=false;return false;}}}});}
this.init();return Aa;},self:function(){return this.reload();},reload:function(){return this.action(2,location.pathname,arguments);},href:function(){this.type="href";return this;},load:function(La,Ma){this.type="load";this.target=La;this.callback=Ma;return this;},popup:function(Na,Oa){this.type="popup";this.opts=Na||this.opts;this.target=Oa||"__POPUP__";return this;},before:function(arguments){return this;},afterReturning:function(Pa){return Pa;}});(function($){'$:nomunge';$.mg=function(){var m={};$.each(arguments,function(){$.each(this,function(k,v){m[k]=v;});});return m;};$.fn.reset=function(){$(this).find("input:text,textarea").val("");};$.fn.form=function(Qa,Ra){var jq=this;if(!Qa)return this;Ra=Ra||"";$.each(Qa,function(Sa,Ta){var Ua=Ra+""+Sa;var Va=jq.find("[name="+Ua+"]");if(Va.length==0){$("<input type=\"hidden\">").attr({name:Ua}).val(Ta).appendTo(jq);}
else{var Wa=Va.get(0).tagName.toUpperCase();var Xa=typeof Va.attr("type")!=="undefined"?Va.attr("type").toUpperCase():null;if(Wa=="INPUT"&&Xa=="RADIO"){Va.each(function(){if(this.value==Ta)$(this).attr("checked","checked");});}
else if(Wa=="INPUT"&&Xa=="CHECKBOX"){if(Ta==true||Ta==Va.val())Va.attr("checked","checked");}
else Va.val(Ta);}});return;};$.fn.s=function(){return this.serialize();};$.fn.sa=function(){return this.serializeArray();};$.fn.so=function(){var Ya={};$.each(this.serializeArray(),function(i,o){var n=o.name,v=o.value;Ya[n]=Ya[n]===undefined?v:$.isArray(Ya[n])?Ya[n].concat(v):[Ya[n],v];});return Ya;};})(jQuery);Array.prototype.indexOf=function(Za,i){i||(i=0);var $a=this.length;if(i<0)i=$a+i;for(;i<$a;i++)if(this[i]===Za)return i;return -1;};Array.prototype.lastIndexOf=function(ab,i){i=isNaN(i)?this.length:(i<0?this.length+i:i)+1;var n=this.slice(0,i).reverse().indexOf(ab);return(n<0)?n:i-n-1;};Array.prototype.remove=function(bb,to){var cb=this.slice((to||bb)+1||this.length);this.length=bb<0?this.length+from:bb;return this.push.apply(this,cb);};Array.prototype.removeItem=function(db){for(var i=0;i<this.length;i++){if(this[i]==db)this.remove(i,i);}};String.prototype.trim=function(){var eb=/(^\s*)|(\s*$)/g;return this.replace(eb,"");};sprintfWrapper={init:function(){if(typeof arguments=="undefined"){return null;}
if(arguments.length<1){return null;}
if(typeof arguments[0]!="string"){return null;}
if(typeof RegExp=="undefined"){return null;}
var fb=arguments[0];var gb=new RegExp(/(%([%]|(\-)?(\+|\x20)?(0)?(\d+)?(\.(\d)?)?([bcdfosxX])))/g);var hb=new Array();var ib=new Array();var jb=0;var kb=0;var lb=0;var mb=0;var nb='';var ob=null;while(ob=gb.exec(fb)){if(ob[9]){jb+=1;}
kb=mb;lb=gb.lastIndex-ob[0].length;ib[ib.length]=fb.substring(kb,lb);mb=gb.lastIndex;hb[hb.length]={match:ob[0],left:ob[3]?true:false,sign:ob[4]||'',pad:ob[5]||' ',min:ob[6]||0,precision:ob[8],code:ob[9]||'%',negative:parseInt(arguments[jb])<0?true:false,argument:String(arguments[jb])};}
ib[ib.length]=fb.substring(mb);if(hb.length==0){return fb;}
if((arguments.length-1)<jb){return null;}
var pb=null;var ob=null;var i=null;for(i=0;i<hb.length;i++){if(hb[i].code=='%'){substitution='%';}
else if(hb[i].code=='b'){hb[i].argument=String(Math.abs(parseInt(hb[i].argument)).toString(2));substitution=sprintfWrapper.convert(hb[i],true);}
else if(hb[i].code=='c'){hb[i].argument=String(String.fromCharCode(parseInt(Math.abs(parseInt(hb[i].argument)))));substitution=sprintfWrapper.convert(hb[i],true);}
else if(hb[i].code=='d'){hb[i].argument=String(Math.abs(parseInt(hb[i].argument)));substitution=sprintfWrapper.convert(hb[i]);}
else if(hb[i].code=='f'){hb[i].argument=String(Math.abs(parseFloat(hb[i].argument)).toFixed(hb[i].precision?hb[i].precision:6));substitution=sprintfWrapper.convert(hb[i]);}
else if(hb[i].code=='o'){hb[i].argument=String(Math.abs(parseInt(hb[i].argument)).toString(8));substitution=sprintfWrapper.convert(hb[i]);}
else if(hb[i].code=='s'){hb[i].argument=hb[i].argument.substring(0,hb[i].precision?hb[i].precision:hb[i].argument.length);substitution=sprintfWrapper.convert(hb[i],true);}
else if(hb[i].code=='x'){hb[i].argument=String(Math.abs(parseInt(hb[i].argument)).toString(16));substitution=sprintfWrapper.convert(hb[i]);}
else if(hb[i].code=='X'){hb[i].argument=String(Math.abs(parseInt(hb[i].argument)).toString(16));substitution=sprintfWrapper.convert(hb[i]).toUpperCase();}
else{substitution=hb[i].match;}
nb+=ib[i];nb+=substitution;}
nb+=ib[i];return nb;},convert:function(qb,rb){if(rb){qb.sign='';}
else{qb.sign=qb.negative?'-':qb.sign;}
var l=qb.min-qb.argument.length+1-qb.sign.length;var sb=new Array(l<0?0:l).join(qb.pad);if(!qb.left){if(qb.pad=="0"||rb){return qb.sign+sb+qb.argument;}
else{return sb+qb.sign+qb.argument;}}
else{if(qb.pad=="0"||rb){return qb.sign+qb.argument+sb.replace(/0/g,' ');}
else{return qb.sign+qb.argument+sb;}}}};sprintf=sprintfWrapper.init;var dateFormat=function(){var tb=/d{1,4}|m{1,4}|yy(?:yy)?|([HhMsTt])\1?|[LloSZ]|"[^"]*"|'[^']*'/g,timezone=/\b(?:[PMCEA][SDP]T|(?:Pacific|Mountain|Central|Eastern|Atlantic) (?:Standard|Daylight|Prevailing) Time|(?:GMT|UTC)(?:[-+]\d{4})?)\b/g,timezoneClip=/[^-+\dA-Z]/g,pad=function(ub,vb){ub=String(ub);vb=vb||2;while(ub.length<vb)ub="0"+ub;return ub;};return function(wb,xb,yb){var dF=dateFormat;if(arguments.length==1&&Object.prototype.toString.call(wb)=="[object String]"&&!/\d/.test(wb)){xb=wb;wb=undefined;}
wb=wb?new Date(wb):new Date;if(isNaN(wb))throw SyntaxError("invalid date");xb=String(dF.masks[xb]||xb||dF.masks["default"]);if(xb.slice(0,4)=="UTC:"){xb=xb.slice(4);yb=true;}
var _=yb?"getUTC":"get",d=wb[_+"Date"](),D=wb[_+"Day"](),m=wb[_+"Month"](),y=wb[_+"FullYear"](),H=wb[_+"Hours"](),M=wb[_+"Minutes"](),s=wb[_+"Seconds"](),L=wb[_+"Milliseconds"](),o=yb?0:wb.getTimezoneOffset(),flags={d:d,dd:pad(d),ddd:dF.i18n.dayNames[D],dddd:dF.i18n.dayNames[D+7],m:m+1,mm:pad(m+1),mmm:dF.i18n.monthNames[m],mmmm:dF.i18n.monthNames[m+12],yy:String(y).slice(2),yyyy:y,h:H%12||12,hh:pad(H%12||12),H:H,HH:pad(H),M:M,MM:pad(M),s:s,ss:pad(s),l:pad(L,3),L:pad(L>99?Math.round(L/10):L),t:H<12?"a":"p",tt:H<12?"am":"pm",T:H<12?"A":"P",TT:H<12?"AM":"PM",Z:yb?"UTC":(String(wb).match(timezone)||[""]).pop().replace(timezoneClip,""),o:(o>0?"-":"+")+pad(Math.floor(Math.abs(o)/60)*100+Math.abs(o)%60,4),S:["th","st","nd","rd"][d%10>3?0:(d%100-d%10!=10)*d%10]};return xb.replace(tb,function($0){return $0 in flags?flags[$0]:$0.slice(1,$0.length-1);});};}();dateFormat.masks={"default":"ddd mmm dd yyyy HH:MM:ss",shortDate:"m/d/yy",mediumDate:"mmm d, yyyy",longDate:"mmmm d, yyyy",fullDate:"dddd, mmmm d, yyyy",shortTime:"h:MM TT",mediumTime:"h:MM:ss TT",longTime:"h:MM:ss TT Z",isoDate:"yyyy-mm-dd",isoTime:"HH:MM:ss",isoDateTime:"yyyy-mm-dd'T'HH:MM:ss",isoUtcDateTime:"UTC:yyyy-mm-dd'T'HH:MM:ss'Z'"};dateFormat.i18n={dayNames:["Sun","Mon","Tue","Wed","Thu","Fri","Sat","Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],monthNames:["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec","January","February","March","April","May","June","July","August","September","October","November","December"]};Date.prototype.format=function(zb,Ab){return dateFormat(this,zb,Ab);};